CREATE USER api_user WITH ENCRYPTED PASSWORD 'apipassword';
CREATE DATABASE api:
GRANT ALL PRIVILIGES ON DATABASE api TO api_user;
CREATE TABLE IF NOT EXISTS api.lessons(id SERIAL PRIMARY KEY, name VARCHAR(255) NOT NULL);
CREATE TABLE IF NOT EXISTS api.themes(lesson_id INT, theme VARCHAR(255), FOREIGN KEY(lesson_id)) REFERENCES lesson(id) ON DELETE CASCADE;
